version: "2"
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    ports:
    - "9000:9000"
    volumes:
    - data-volume:/data/app
    - ./dockerData:/data/app
volumes:
  data-volume:
